version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./config/mimoto-issuers-config.json:/config/server/mimoto-issuers-config.json
      - ./config/CredentialTemplate.html:/config/server/CredentialTemplate.html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./config/sunbirdFallback.json:/config/server/sunbirdFallback.json
      - ./config/mosipFallback.json:/config/server/mosipFallback.json
      - ./config/mockIdaFallback.json:/config/server/mockIdaFallback.json
  mimoto-service:
    container_name: 'Mimoto-Service'
    image: 'mosipid/mimoto:0.12.0'
    user: root
    ports:
      - '8099:8099'
    environment:
      - container_user=mosip
      - active_profile_env=default
      - SPRING_CONFIG_NAME=mimoto
      - SPRING_CONFIG_LOCATION=/home/mosip/
    volumes:
      - ./config/mimoto-default.properties:/home/mosip/mimoto-default.properties
      - ./config/mimoto-issuers-config.json:/home/mosip/mimoto-issuers-config.json
      - ./certs/oidckeystore.p12:/home/mosip/certs/oidckeystore.p12
      - ./loader_path/:/home/mosip/additional_jars/
    depends_on:
      - nginx